#ifndef YATLD_SETTINGS_H_
#define YATLD_SETTINGS_H_

#include <opencv.hpp>

//#define MIN_BB_AREA 50
#define MIN_BB_SIDE 15
#define STEP_H 0.1
#define STEP_V 0.1
#define STEP_S 1.2

#define INIT_SHIFT_CHANGE 0.01f
#define INIT_SCALE_CHANGE 0.01f
#define INIT_ROTATION_CHANGE 10.0f //* CV_PI / 180.0
#define INIT_SYNTHESIS_NUM 20
#define INIT_POSITIVE_NUM 10
#define INIT_NEGATIVE_NUM 100	//?
#define INIT_GAUSSIAN_SIGMA 5
#define PN_POSITIVE_OVERLAP 0.6 //too small?
#define PN_NEGATIVE_OVERLAP 0.2
//#define PN_NEGATIVE_MIN_SCALE 0.5 //relative to init bounding box **

#define NUM_FERNS 10
#define NUM_FERN_FEATURES 13
#define FERN_INDEX_SIZE 8192	//2^13 = 8192
#define FERN_GAUSSIAN_SIGMA 3

#define NORMALIZED_PATCH_SIZE 15
#define NN_THRESHOLD 0.6
#define NN_MAX_POSITIVE 600  
#define NN_MIN_POSITIVE 300
#define NN_MAX_NEGATIVE 200
#define NN_MIN_NEGATIVE 100

#define TRACKER_GRID_POINT_NUM_H 10
#define TRACKER_GRID_POINT_NUM_V 10
#define TRACKER_GRID_PATCH_SIZE 10
#define LK_WINDOW_SIZE 4
#define LK_LEVEL 5
#define LK_TERM_COUNT 20
#define LK_TERM_EPSILON 0.03
#define LK_DERIV_LAMBDA 0.5
#define LK_FAILURE_RESIDUAL 10

#define TRAINER_CORE_THRESHOLD 0.6
#define TRAINER_MARGIN_THRESHOLD 0.0
#define UPDATE_SHIFT_CHANGE 0.01f
#define UPDATE_SCALE_CHANGE 0.01f
#define UPDATE_ROTATION_CHANGE 5.0f //10.0 //* CV_PI / 180.0
#define UPDATE_SYNTHESIS_NUM 10
#define UPDATE_GAUSSIAN_SIGMA 5
#define UPDATE_POSITIVE_NUM 10
#define UPDATE_NEGATIVE_NUM 100	//?

#endif
